package com.solace.connector.db.pull.entity;
// Generated Sep 28, 2023, 3:52:21 PM by Hibernate Tools 5.6.2.Final


import java.math.BigDecimal;
import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * PSbyOpentripAllocReqId generated by hbm2java
 */
@Embeddable
public class PSbyOpentripAllocReqId  implements java.io.Serializable {


     private BigDecimal reqId;
     private String pairRef;
     private Date pairDate;
     private Character crewType;
     private String fleet;
     private String rank;
     private String crewSelected;
     private Character status;
     private Date createdOn;
     private Date modOn;
     private String loggedBy;
     private String adbSubject;
     private BigDecimal adbSequence;
     private BigDecimal adbSetSequence;
     private Date adbTimestamp;
     private BigDecimal adbOpcode;
     private BigDecimal adbUpdateAll;
     private String adbRefObject;
     private Character adbLDeliveryStatus;
     private BigDecimal adbLCmsequence;
     private String adbTrackingid;

    public PSbyOpentripAllocReqId() {
    }

	
    public PSbyOpentripAllocReqId(BigDecimal adbSequence, BigDecimal adbOpcode) {
        this.adbSequence = adbSequence;
        this.adbOpcode = adbOpcode;
    }
    public PSbyOpentripAllocReqId(BigDecimal reqId, String pairRef, Date pairDate, Character crewType, String fleet, String rank, String crewSelected, Character status, Date createdOn, Date modOn, String loggedBy, String adbSubject, BigDecimal adbSequence, BigDecimal adbSetSequence, Date adbTimestamp, BigDecimal adbOpcode, BigDecimal adbUpdateAll, String adbRefObject, Character adbLDeliveryStatus, BigDecimal adbLCmsequence, String adbTrackingid) {
       this.reqId = reqId;
       this.pairRef = pairRef;
       this.pairDate = pairDate;
       this.crewType = crewType;
       this.fleet = fleet;
       this.rank = rank;
       this.crewSelected = crewSelected;
       this.status = status;
       this.createdOn = createdOn;
       this.modOn = modOn;
       this.loggedBy = loggedBy;
       this.adbSubject = adbSubject;
       this.adbSequence = adbSequence;
       this.adbSetSequence = adbSetSequence;
       this.adbTimestamp = adbTimestamp;
       this.adbOpcode = adbOpcode;
       this.adbUpdateAll = adbUpdateAll;
       this.adbRefObject = adbRefObject;
       this.adbLDeliveryStatus = adbLDeliveryStatus;
       this.adbLCmsequence = adbLCmsequence;
       this.adbTrackingid = adbTrackingid;
    }
   


    @Column(name="REQ_ID", precision=22, scale=0)
    public BigDecimal getReqId() {
        return this.reqId;
    }
    
    public void setReqId(BigDecimal reqId) {
        this.reqId = reqId;
    }


    @Column(name="PAIR_REF", length=25)
    public String getPairRef() {
        return this.pairRef;
    }
    
    public void setPairRef(String pairRef) {
        this.pairRef = pairRef;
    }


    @Column(name="PAIR_DATE", length=7)
    public Date getPairDate() {
        return this.pairDate;
    }
    
    public void setPairDate(Date pairDate) {
        this.pairDate = pairDate;
    }


    @Column(name="CREW_TYPE", length=1)
    public Character getCrewType() {
        return this.crewType;
    }
    
    public void setCrewType(Character crewType) {
        this.crewType = crewType;
    }


    @Column(name="FLEET", length=50)
    public String getFleet() {
        return this.fleet;
    }
    
    public void setFleet(String fleet) {
        this.fleet = fleet;
    }


    @Column(name="RANK", length=10)
    public String getRank() {
        return this.rank;
    }
    
    public void setRank(String rank) {
        this.rank = rank;
    }


    @Column(name="CREW_SELECTED", length=20)
    public String getCrewSelected() {
        return this.crewSelected;
    }
    
    public void setCrewSelected(String crewSelected) {
        this.crewSelected = crewSelected;
    }


    @Column(name="STATUS", length=1)
    public Character getStatus() {
        return this.status;
    }
    
    public void setStatus(Character status) {
        this.status = status;
    }


    @Column(name="CREATED_ON", length=7)
    public Date getCreatedOn() {
        return this.createdOn;
    }
    
    public void setCreatedOn(Date createdOn) {
        this.createdOn = createdOn;
    }


    @Column(name="MOD_ON", length=7)
    public Date getModOn() {
        return this.modOn;
    }
    
    public void setModOn(Date modOn) {
        this.modOn = modOn;
    }


    @Column(name="LOGGED_BY", length=25)
    public String getLoggedBy() {
        return this.loggedBy;
    }
    
    public void setLoggedBy(String loggedBy) {
        this.loggedBy = loggedBy;
    }


    @Column(name="ADB_SUBJECT")
    public String getAdbSubject() {
        return this.adbSubject;
    }
    
    public void setAdbSubject(String adbSubject) {
        this.adbSubject = adbSubject;
    }


    @Column(name="ADB_SEQUENCE", nullable=false, precision=22, scale=0)
    public BigDecimal getAdbSequence() {
        return this.adbSequence;
    }
    
    public void setAdbSequence(BigDecimal adbSequence) {
        this.adbSequence = adbSequence;
    }


    @Column(name="ADB_SET_SEQUENCE", precision=22, scale=0)
    public BigDecimal getAdbSetSequence() {
        return this.adbSetSequence;
    }
    
    public void setAdbSetSequence(BigDecimal adbSetSequence) {
        this.adbSetSequence = adbSetSequence;
    }


    @Column(name="ADB_TIMESTAMP", length=13)
    public Date getAdbTimestamp() {
        return this.adbTimestamp;
    }
    
    public void setAdbTimestamp(Date adbTimestamp) {
        this.adbTimestamp = adbTimestamp;
    }


    @Column(name="ADB_OPCODE", nullable=false, precision=22, scale=0)
    public BigDecimal getAdbOpcode() {
        return this.adbOpcode;
    }
    
    public void setAdbOpcode(BigDecimal adbOpcode) {
        this.adbOpcode = adbOpcode;
    }


    @Column(name="ADB_UPDATE_ALL", precision=22, scale=0)
    public BigDecimal getAdbUpdateAll() {
        return this.adbUpdateAll;
    }
    
    public void setAdbUpdateAll(BigDecimal adbUpdateAll) {
        this.adbUpdateAll = adbUpdateAll;
    }


    @Column(name="ADB_REF_OBJECT", length=64)
    public String getAdbRefObject() {
        return this.adbRefObject;
    }
    
    public void setAdbRefObject(String adbRefObject) {
        this.adbRefObject = adbRefObject;
    }


    @Column(name="ADB_L_DELIVERY_STATUS", length=1)
    public Character getAdbLDeliveryStatus() {
        return this.adbLDeliveryStatus;
    }
    
    public void setAdbLDeliveryStatus(Character adbLDeliveryStatus) {
        this.adbLDeliveryStatus = adbLDeliveryStatus;
    }


    @Column(name="ADB_L_CMSEQUENCE", precision=38, scale=0)
    public BigDecimal getAdbLCmsequence() {
        return this.adbLCmsequence;
    }
    
    public void setAdbLCmsequence(BigDecimal adbLCmsequence) {
        this.adbLCmsequence = adbLCmsequence;
    }


    @Column(name="ADB_TRACKINGID", length=40)
    public String getAdbTrackingid() {
        return this.adbTrackingid;
    }
    
    public void setAdbTrackingid(String adbTrackingid) {
        this.adbTrackingid = adbTrackingid;
    }


   public boolean equals(Object other) {
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof PSbyOpentripAllocReqId) ) return false;
		 PSbyOpentripAllocReqId castOther = ( PSbyOpentripAllocReqId ) other; 
         
		 return ( (this.getReqId()==castOther.getReqId()) || ( this.getReqId()!=null && castOther.getReqId()!=null && this.getReqId().equals(castOther.getReqId()) ) )
 && ( (this.getPairRef()==castOther.getPairRef()) || ( this.getPairRef()!=null && castOther.getPairRef()!=null && this.getPairRef().equals(castOther.getPairRef()) ) )
 && ( (this.getPairDate()==castOther.getPairDate()) || ( this.getPairDate()!=null && castOther.getPairDate()!=null && this.getPairDate().equals(castOther.getPairDate()) ) )
 && ( (this.getCrewType()==castOther.getCrewType()) || ( this.getCrewType()!=null && castOther.getCrewType()!=null && this.getCrewType().equals(castOther.getCrewType()) ) )
 && ( (this.getFleet()==castOther.getFleet()) || ( this.getFleet()!=null && castOther.getFleet()!=null && this.getFleet().equals(castOther.getFleet()) ) )
 && ( (this.getRank()==castOther.getRank()) || ( this.getRank()!=null && castOther.getRank()!=null && this.getRank().equals(castOther.getRank()) ) )
 && ( (this.getCrewSelected()==castOther.getCrewSelected()) || ( this.getCrewSelected()!=null && castOther.getCrewSelected()!=null && this.getCrewSelected().equals(castOther.getCrewSelected()) ) )
 && ( (this.getStatus()==castOther.getStatus()) || ( this.getStatus()!=null && castOther.getStatus()!=null && this.getStatus().equals(castOther.getStatus()) ) )
 && ( (this.getCreatedOn()==castOther.getCreatedOn()) || ( this.getCreatedOn()!=null && castOther.getCreatedOn()!=null && this.getCreatedOn().equals(castOther.getCreatedOn()) ) )
 && ( (this.getModOn()==castOther.getModOn()) || ( this.getModOn()!=null && castOther.getModOn()!=null && this.getModOn().equals(castOther.getModOn()) ) )
 && ( (this.getLoggedBy()==castOther.getLoggedBy()) || ( this.getLoggedBy()!=null && castOther.getLoggedBy()!=null && this.getLoggedBy().equals(castOther.getLoggedBy()) ) )
 && ( (this.getAdbSubject()==castOther.getAdbSubject()) || ( this.getAdbSubject()!=null && castOther.getAdbSubject()!=null && this.getAdbSubject().equals(castOther.getAdbSubject()) ) )
 && ( (this.getAdbSequence()==castOther.getAdbSequence()) || ( this.getAdbSequence()!=null && castOther.getAdbSequence()!=null && this.getAdbSequence().equals(castOther.getAdbSequence()) ) )
 && ( (this.getAdbSetSequence()==castOther.getAdbSetSequence()) || ( this.getAdbSetSequence()!=null && castOther.getAdbSetSequence()!=null && this.getAdbSetSequence().equals(castOther.getAdbSetSequence()) ) )
 && ( (this.getAdbTimestamp()==castOther.getAdbTimestamp()) || ( this.getAdbTimestamp()!=null && castOther.getAdbTimestamp()!=null && this.getAdbTimestamp().equals(castOther.getAdbTimestamp()) ) )
 && ( (this.getAdbOpcode()==castOther.getAdbOpcode()) || ( this.getAdbOpcode()!=null && castOther.getAdbOpcode()!=null && this.getAdbOpcode().equals(castOther.getAdbOpcode()) ) )
 && ( (this.getAdbUpdateAll()==castOther.getAdbUpdateAll()) || ( this.getAdbUpdateAll()!=null && castOther.getAdbUpdateAll()!=null && this.getAdbUpdateAll().equals(castOther.getAdbUpdateAll()) ) )
 && ( (this.getAdbRefObject()==castOther.getAdbRefObject()) || ( this.getAdbRefObject()!=null && castOther.getAdbRefObject()!=null && this.getAdbRefObject().equals(castOther.getAdbRefObject()) ) )
 && ( (this.getAdbLDeliveryStatus()==castOther.getAdbLDeliveryStatus()) || ( this.getAdbLDeliveryStatus()!=null && castOther.getAdbLDeliveryStatus()!=null && this.getAdbLDeliveryStatus().equals(castOther.getAdbLDeliveryStatus()) ) )
 && ( (this.getAdbLCmsequence()==castOther.getAdbLCmsequence()) || ( this.getAdbLCmsequence()!=null && castOther.getAdbLCmsequence()!=null && this.getAdbLCmsequence().equals(castOther.getAdbLCmsequence()) ) )
 && ( (this.getAdbTrackingid()==castOther.getAdbTrackingid()) || ( this.getAdbTrackingid()!=null && castOther.getAdbTrackingid()!=null && this.getAdbTrackingid().equals(castOther.getAdbTrackingid()) ) );
   }
   
   public int hashCode() {
         int result = 17;
         
         result = 37 * result + ( getReqId() == null ? 0 : this.getReqId().hashCode() );
         result = 37 * result + ( getPairRef() == null ? 0 : this.getPairRef().hashCode() );
         result = 37 * result + ( getPairDate() == null ? 0 : this.getPairDate().hashCode() );
         result = 37 * result + ( getCrewType() == null ? 0 : this.getCrewType().hashCode() );
         result = 37 * result + ( getFleet() == null ? 0 : this.getFleet().hashCode() );
         result = 37 * result + ( getRank() == null ? 0 : this.getRank().hashCode() );
         result = 37 * result + ( getCrewSelected() == null ? 0 : this.getCrewSelected().hashCode() );
         result = 37 * result + ( getStatus() == null ? 0 : this.getStatus().hashCode() );
         result = 37 * result + ( getCreatedOn() == null ? 0 : this.getCreatedOn().hashCode() );
         result = 37 * result + ( getModOn() == null ? 0 : this.getModOn().hashCode() );
         result = 37 * result + ( getLoggedBy() == null ? 0 : this.getLoggedBy().hashCode() );
         result = 37 * result + ( getAdbSubject() == null ? 0 : this.getAdbSubject().hashCode() );
         result = 37 * result + ( getAdbSequence() == null ? 0 : this.getAdbSequence().hashCode() );
         result = 37 * result + ( getAdbSetSequence() == null ? 0 : this.getAdbSetSequence().hashCode() );
         result = 37 * result + ( getAdbTimestamp() == null ? 0 : this.getAdbTimestamp().hashCode() );
         result = 37 * result + ( getAdbOpcode() == null ? 0 : this.getAdbOpcode().hashCode() );
         result = 37 * result + ( getAdbUpdateAll() == null ? 0 : this.getAdbUpdateAll().hashCode() );
         result = 37 * result + ( getAdbRefObject() == null ? 0 : this.getAdbRefObject().hashCode() );
         result = 37 * result + ( getAdbLDeliveryStatus() == null ? 0 : this.getAdbLDeliveryStatus().hashCode() );
         result = 37 * result + ( getAdbLCmsequence() == null ? 0 : this.getAdbLCmsequence().hashCode() );
         result = 37 * result + ( getAdbTrackingid() == null ? 0 : this.getAdbTrackingid().hashCode() );
         return result;
   }   


}


