package com.solace.connector.db.pull.entity;
// Generated Sep 28, 2023, 3:52:21 PM by Hibernate Tools 5.6.2.Final


import java.math.BigDecimal;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.UniqueConstraint;

/**
 * SbyOpentripAllocReq generated by hbm2java
 */
@Entity
@Table(name="SBY_OPENTRIP_ALLOC_REQ"
    
    , uniqueConstraints = @UniqueConstraint(columnNames="REQ_ID") 
)
public class SbyOpentripAllocReq  implements java.io.Serializable {


     private BigDecimal reqId;

    public SbyOpentripAllocReq() {
    }

    public SbyOpentripAllocReq(BigDecimal reqId) {
       this.reqId = reqId;
    }
   
     @Id 

    
    @Column(name="REQ_ID", unique=true, precision=22, scale=0)
    public BigDecimal getReqId() {
        return this.reqId;
    }
    
    public void setReqId(BigDecimal reqId) {
        this.reqId = reqId;
    }




}


