package com.solace.connector.db.pull.entity;
// Generated Sep 28, 2023, 3:52:21 PM by Hibernate Tools 5.6.2.Final


import java.math.BigDecimal;
import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * SbyOpentripAllocId generated by hbm2java
 */
@Embeddable
public class SbyOpentripAllocId  implements java.io.Serializable {


     private BigDecimal staffId;
     private Character status;
     private Date createdOn;
     private Date modOn;
     private String loggedBy;
     private String reason;
     private BigDecimal reqId;

    public SbyOpentripAllocId() {
    }

    public SbyOpentripAllocId(BigDecimal staffId, Character status, Date createdOn, Date modOn, String loggedBy, String reason, BigDecimal reqId) {
       this.staffId = staffId;
       this.status = status;
       this.createdOn = createdOn;
       this.modOn = modOn;
       this.loggedBy = loggedBy;
       this.reason = reason;
       this.reqId = reqId;
    }
   


    @Column(name="STAFF_ID", precision=22, scale=0)
    public BigDecimal getStaffId() {
        return this.staffId;
    }
    
    public void setStaffId(BigDecimal staffId) {
        this.staffId = staffId;
    }


    @Column(name="STATUS", length=1)
    public Character getStatus() {
        return this.status;
    }
    
    public void setStatus(Character status) {
        this.status = status;
    }


    @Column(name="CREATED_ON", length=7)
    public Date getCreatedOn() {
        return this.createdOn;
    }
    
    public void setCreatedOn(Date createdOn) {
        this.createdOn = createdOn;
    }


    @Column(name="MOD_ON", length=7)
    public Date getModOn() {
        return this.modOn;
    }
    
    public void setModOn(Date modOn) {
        this.modOn = modOn;
    }


    @Column(name="LOGGED_BY", length=25)
    public String getLoggedBy() {
        return this.loggedBy;
    }
    
    public void setLoggedBy(String loggedBy) {
        this.loggedBy = loggedBy;
    }


    @Column(name="REASON", length=4000)
    public String getReason() {
        return this.reason;
    }
    
    public void setReason(String reason) {
        this.reason = reason;
    }


    @Column(name="REQ_ID", precision=22, scale=0)
    public BigDecimal getReqId() {
        return this.reqId;
    }
    
    public void setReqId(BigDecimal reqId) {
        this.reqId = reqId;
    }


   public boolean equals(Object other) {
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof SbyOpentripAllocId) ) return false;
		 SbyOpentripAllocId castOther = ( SbyOpentripAllocId ) other; 
         
		 return ( (this.getStaffId()==castOther.getStaffId()) || ( this.getStaffId()!=null && castOther.getStaffId()!=null && this.getStaffId().equals(castOther.getStaffId()) ) )
 && ( (this.getStatus()==castOther.getStatus()) || ( this.getStatus()!=null && castOther.getStatus()!=null && this.getStatus().equals(castOther.getStatus()) ) )
 && ( (this.getCreatedOn()==castOther.getCreatedOn()) || ( this.getCreatedOn()!=null && castOther.getCreatedOn()!=null && this.getCreatedOn().equals(castOther.getCreatedOn()) ) )
 && ( (this.getModOn()==castOther.getModOn()) || ( this.getModOn()!=null && castOther.getModOn()!=null && this.getModOn().equals(castOther.getModOn()) ) )
 && ( (this.getLoggedBy()==castOther.getLoggedBy()) || ( this.getLoggedBy()!=null && castOther.getLoggedBy()!=null && this.getLoggedBy().equals(castOther.getLoggedBy()) ) )
 && ( (this.getReason()==castOther.getReason()) || ( this.getReason()!=null && castOther.getReason()!=null && this.getReason().equals(castOther.getReason()) ) )
 && ( (this.getReqId()==castOther.getReqId()) || ( this.getReqId()!=null && castOther.getReqId()!=null && this.getReqId().equals(castOther.getReqId()) ) );
   }
   
   public int hashCode() {
         int result = 17;
         
         result = 37 * result + ( getStaffId() == null ? 0 : this.getStaffId().hashCode() );
         result = 37 * result + ( getStatus() == null ? 0 : this.getStatus().hashCode() );
         result = 37 * result + ( getCreatedOn() == null ? 0 : this.getCreatedOn().hashCode() );
         result = 37 * result + ( getModOn() == null ? 0 : this.getModOn().hashCode() );
         result = 37 * result + ( getLoggedBy() == null ? 0 : this.getLoggedBy().hashCode() );
         result = 37 * result + ( getReason() == null ? 0 : this.getReason().hashCode() );
         result = 37 * result + ( getReqId() == null ? 0 : this.getReqId().hashCode() );
         return result;
   }   


}


